### PR TITLE
pass env vars on spin up command

### PR DESCRIPTION
**Pull request by michelleN**

### CODE REVIEW

**Review by fibonacci1729 — APPROVED** [review]
This looks great. There is a snippet in the README that mentions adding the environment variables to spin.toml, could you remove that in this PR too?

**Comment by fibonacci1729** [comment]
Could you delete the README in the example? It currently doesn't have any useful content and I missed removing it during my last cleanup.

**Comment by michelleN** [comment]
just removed the example/README and pushed!

**Comment by kate-goldenring** [comment]
@michelleN did we mean to remove the env vars from the spin.toml here?

**Comment by michelleN** [comment]
@kate-goldenring yea. do you think we need them?

**Pull request merged**
